# Generated by Django 5.1.6 on 2025-03-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectExamHallMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='seating.examhall')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_hall_mappings', to='seating.subject')),
            ],
            options={
                'unique_together': {('subject', 'exam_hall')},
            },
        ),
    ]
