# Generated by Django 5.1.6 on 2025-03-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'class_name')},
            },
        ),
    ]
