# Generated by Django 5.1.6 on 2025-03-05 06:15

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to=events.models.upload_to_event_images),
        ),
    ]
